Feat/add oauth route
IgnacioBarraza/BlackSharkWeb_Backend pull request #1
Opened 2024-12-11 15:52 UTC by JoelFaldin

# Añadir ruta para google auth

## ¿Por qué se hizo? 🥸

🔗 Para que el sistema pueda guardar aquellos usuarios que intenten iniciar sesión con google.

## ¿Qué se hizo? 🪚

Se agregó una nueva ruta en loginRouter, la cual verifica si el email del usuario existe en la base de datos. Si no existe, se creará el registro con una contraseña encriptada, pero no hasheada (debido a que el proceso del login siempre intenta verificar la contraseña por medio de hashes, la nueva contraseña no coincidirá nunca, haciendo que solo se pueda iniciar sesión mediante google).
También, en la ruta api/login/verify (la que se utiliza para iniciar sesión normalmente) y en la nueva ruta agregada, se devolverá un nuevo atributo `method`, el cual indicará si el usuario inició sesión con firebase. El atributo se utilizará en el frontend para cerrar la sesión.

## ¿Cómo se prueba esto? 🧪

1- `npm i` y `npm run dev`.
2- Hacer una request a /api/login/oauth, pasando en el body un correo y un nombre de usuario:
```
{
	"email": "email",
	"username": "username"
}
```
4- Si el usuario no existe, debería aparecer un mensaje informando que se creó y verificó el usuario. En caso de que el usuario sí exista, debería devolver que el usuario fue verificado. En ambios casos, deben estar los atributos `message`, `token`, `username`, `tipo_user`, `user_id` y `method`.

2024-12-11 22:52 UTC, IgnacioBarraza requested changes
Los comentarios que deje

2024-12-11 22:52 UTC, IgnacioBarraza commented on src/routes/loginRouter.ts
> +                contrasenha: encrypt(),
No entiendo porque estas guardando el correo que se registra con google con una contraseña encriptada, no entiendo el motivo de guardar el correo, si despues el usuario intenta iniciar sesión fuera de google, va a encontrar que no puede ingresar y van a empezar a llover los errores, revisa esto

2024-12-11 22:52 UTC, IgnacioBarraza commented on src/routes/loginRouter.ts
> +                    return res.status(200).json({ message: 'Usuario verificado con exito. Redirigiendo...', token, username: user[0].username, tipo_user: user[0].tipo_user, user_id: user[0].id_usuari
a que hace referencia el metodo 'custom'?

2024-12-11 22:52 UTC, IgnacioBarraza commented on src/routes/loginRouter.ts
> +                return res.status(200).json({ message: 'Usuario verificado con exito. Redirigiendo...', token, username: user[0].username, tipo_user: user[0].tipo_user, user_id: user[0].id_usuario, m
Descompone los valores que te llegan tanto en el body como los que te devuelve user, mala práctica usar `user[0].username` y asi, es más facil tener centralizado en un solo lugar los valores y modificarlos desde ahi

2024-12-16 02:50 UTC, JoelFaldin commented on src/routes/loginRouter.ts
> +                    return res.status(200).json({ message: 'Usuario verificado con exito. Redirigiendo...', token, username: user[0].username, tipo_user: user[0].tipo_user, user_id: user[0].id_usuari
Es para diferenciar usuarios que inicien sesión con google o con el login normal del backend (route handler /verify). El único propósito que tiene es que en el frontend, se pueda decidir si usar el logout de google o el normal. Qué pasa si el usuario inicia sesión sin google, y quiere cerrar sesión? Al menos yo encontré bastante cómodo devolver esa información del backend y tenerla a mano en cualquier momento jajajaj

2024-12-16 03:03 UTC, JoelFaldin commented on src/routes/loginRouter.ts
> +                return res.status(200).json({ message: 'Usuario verificado con exito. Redirigiendo...', token, username: user[0].username, tipo_user: user[0].tipo_user, user_id: user[0].id_usuario, m
oki

2024-12-16 03:15 UTC, JoelFaldin commented on src/routes/loginRouter.ts
> +                contrasenha: encrypt(),
Piensa en cuando un usuario inicia sesión con google, luego cierra sesión, y después intenta entrar usando el login normal (del route handler /verify). Tendría que crearse una cuenta nueva, sería contraintuitivo tener que crear la cuenta cuando ya se inició sesión con google. Además, ¿cómo funcionaría el tema de los pedidos con el login de google, si esos utilizan la id del usuario?
Por cierto, para evitar eso de los errores que mencionas, bancaría implementar una funcionalidad que devuelva un mensaje custom tipo "Has iniciado sesión con google anteriormente. Si quieres iniciar sesión del otro modo, reestablece la contraseña" y haga un redirect hacia esa ruta del frontend. Eso se puede hacer revisando el comienzo de la contraseña: los que creen su cuenta e inicien sesión con /verify su password empieza por $2b$..., los que inican sesión con google y /oauth tienen un string random

2024-12-16 03:17 UTC, JoelFaldin commented on src/routes/loginRouter.ts
> +                return res.status(200).json({ message: 'Usuario verificado con exito. Redirigiendo...', token, username: user[0].username, tipo_user: user[0].tipo_user, user_id: user[0].id_usuario, m
btw casi todas las rutas utilizan el `user[0].property`, podría hacerse un repaso general de todo el backend desestructurando los objetos. Además, se podría aprovechar para quitar los endpoints que no se utilicen y mejorar los imports usando el `tsconfig.json` y los path aliases que están super nice :D

2024-12-16 03:29 UTC, IgnacioBarraza commented on src/routes/loginRouter.ts
> +                contrasenha: encrypt(),
yaya, ya entendi a que te refieres, lo de informar que el usuario inicio con google esta weno, habria que verlo en un futuro, por ahora no es necesario

2024-12-16 03:29 UTC, IgnacioBarraza commented on src/routes/loginRouter.ts
> +                return res.status(200).json({ message: 'Usuario verificado con exito. Redirigiendo...', token, username: user[0].username, tipo_user: user[0].tipo_user, user_id: user[0].id_usuario, m
oka, entonces dejamos ese refactor para más adelante

2024-12-16 03:30 UTC, IgnacioBarraza approved these changes
good

2024-12-16 03:31 UTC, merged